### ISSUE TITLE
Context used when formatting the quizzes names

### ISSUE THREAD

**Issue by mudrd8mz** [timhunt/moodle-availability_quizquestion#1]
It caught my eye to see that `availability_quizquestion::get_javascript_init_params()` returns the quiz names processed by `format_string()` in the context of the current course.

From what I can see in the `core_course_renderer::course_section_cm_name_title()` the module names on the course main page are normally formatted in the context of the modules themselves. A chance to get different output is minimal, yet I am wondering what context should be used.

This should be easily testable by enabling some filters in the context of one quiz only, make it so that the filter affects the quiz name, and see how it is displayed in the course main page and how in the selector.

**Comment by timhunt** [comment]
Thanks David. It seems that we started by copying availability_group, and this line never got updated when we changed everything else.

**Comment by timhunt** [comment]
Fix done.
