### ISSUE TITLE
Improvement: Add Moodle 3.5 to 3.7 as compatible

### ISSUE THREAD

**Issue by germanvaleroelizondo** [timhunt/moodle-availability_quizquestion#3]
Congratulations on another new useful plugin.
I forked this plugin and changed the required Moodle branch to Moodle 3.5 (2018051700) in order to test it in a local Moodle server before installing it in my University (Moodle 3.5) server.
It worked well !
I think this plugin would be even greater if you can make the proper tests for compatibility with older Moodle branches (3.5 to 3.7) and, if passed, mark these branched as supported.

![Available URL resource](https://user-images.githubusercontent.com/2671923/91617698-2d99da80-e94e-11ea-8014-bf5742ceac31.jpg)

![NOT Available URL resource](https://user-images.githubusercontent.com/2671923/91617722-3b4f6000-e94e-11ea-971c-33ec18422553.jpg)

Thanks in advance

**Comment by timhunt** [comment]
Thanks.

**Comment by germanvaleroelizondo** [comment]
Thank you.
